language: ruby
rvm:
  - 2.3.2
  - ruby-head
bundler_args: --jobs 1 --retry 3

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec rubocop .
  - RAILS_ENV=test bundle exec rake

